version: "3"
services:
  app:
    build: .
    command: /bin/sh -c "cd /srv/app && composer install && composer update && apache2-foreground"
    image: breakout-docker
    ports:
      - ${BREAKOUT_PORT:-9001}:80
    volumes:
      - ./src:/srv/app
    user: "1000:1000"
